"""Initial StudyFlow schema

Revision ID: 7d327d8dafc4
Revises:
Create Date: 2026-09-10 14:05:03.155139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d327d8dafc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_limit',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('failures', sa.JSON(), nullable=False),
    sa.Column('blocked_until', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_user_id'), ['user_id'], unique=False)

    op.create_table('login_session',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('ai_requested_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash')
    )
    with op.batch_alter_table('login_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_session_expires_at'), ['expires_at'], unique=False)

    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('due_at', sa.DateTime(), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=True),
    sa.CheckConstraint("priority IN ('High','Medium','Low')", name='assignment_priority'),
    sa.CheckConstraint("status IN ('Not Started','In Progress','Completed')", name='assignment_status'),
    sa.CheckConstraint('estimated_minutes BETWEEN 1 AND 10080', name='assignment_minutes'),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignment_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_due_at'), ['due_at'], unique=False)

    op.create_table('study_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.CheckConstraint('minutes BETWEEN 1 AND 240', name='session_minutes'),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_session_assignment_id'), ['assignment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_session_starts_at'), ['starts_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_session_starts_at'))
        batch_op.drop_index(batch_op.f('ix_study_session_assignment_id'))

    op.drop_table('study_session')
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignment_due_at'))
        batch_op.drop_index(batch_op.f('ix_assignment_course_id'))

    op.drop_table('assignment')
    with op.batch_alter_table('login_session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_session_expires_at'))

    op.drop_table('login_session')
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_user_id'))

    op.drop_table('course')
    op.drop_table('user')
    op.drop_table('login_limit')
    # ### end Alembic commands ###
